version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
      - ./data:/app/data:ro
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - WORKERS=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/inference/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    restart: unless-stopped

networks:
  default:
    name: starharbor-network
